name: Release Windows Installer

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions: write-all

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.5'

      - name: Build executable
        run: go build -o TheOtherRolesInstaller-Windows.exe main.go

      - name: Upload Release Asset
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: 'TheOtherRolesInstaller-Windows.exe'
          name: 'Build ${{ github.run_number }}'
          tag: 'build-${{ github.run_number }}'
